/* Enums */

export const Role = {
    ADMIN: "ADMIN",
    MANAGER: "MANAGER",
    MEMBER: "MEMBER",
    GUEST: "GUEST",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const MealSlot = {
    BREAKFAST: "BREAKFAST",
    LUNCH: "LUNCH",
    DINNER: "DINNER",
} as const;

export type MealSlot = (typeof MealSlot)[keyof typeof MealSlot];

export const ExpenseCategory = {
    PROTEIN: "PROTEIN",
    CARB: "CARB",
    VEGETABLE: "VEGETABLE",
    SPICE: "SPICE",
    OIL: "OIL",
    UTILITY: "UTILITY",
    OTHER: "OTHER",
} as const;

export type ExpenseCategory =
    (typeof ExpenseCategory)[keyof typeof ExpenseCategory];

export const MonthStatus = {
    OPEN: "OPEN",
    CLOSED: "CLOSED",
} as const;

export type MonthStatus = (typeof MonthStatus)[keyof typeof MonthStatus];

/* Entities */

export interface Mess {
    id: string;
    name: string;
    inviteCode: string;
    cutOffTime: string;
    monthStartDay: number;
    isActive: boolean;
    estimatedMonthlyBudget?: number;
    createdAt: string;
}

export interface Member {
    id: string;
    messId: string;
    name: string;
    phone?: string;
    telegramUid?: number;
    telegramLinked: boolean;
    role: Role;
    isActive: boolean;
    isGuest: boolean;
    guestFrom?: string;
    guestUntil?: string;
    balance: number;
}

export interface DailyLog {
    id: string;
    memberId: string;
    date: string;
    breakfastCount: number;
    lunchCount: number;
    dinnerCount: number;
    /** Convenience booleans: count > 0 */
    breakfast: boolean;
    lunch: boolean;
    dinner: boolean;
    guestCount: number;
    frozen: boolean;
    /** false = auto-generated by cron from preferences; true = manually changed */
    isOverride?: boolean;
    overrideType?: string | null;
}

export interface MealConfig {
    id: string;
    messId: string;
    mealType: "BREAKFAST" | "LUNCH" | "DINNER";
    enabled: boolean;
    cutoffTime: string; // HH:MM
    maxCount: number;
}

export interface Expense {
    id: string;
    messId: string;
    memberId: string | null;
    memberName?: string;
    amount: number;
    category: ExpenseCategory;
    description: string;
    date: string;
    createdAt: string;
}

export interface MonthlySnapshot {
    id: string;
    messId: string;
    yearMonth: string;
    totalExpense: number;
    mealRate: number;
    totalMeals: number;
    isClosed: boolean;
    closedAt?: string;
}

export interface AuditTrail {
    id: string;
    adminId: string;
    adminName?: string;
    entityType: string;
    entityId: string;
    oldValue: string;
    newValue: string;
    reason: string;
    createdAt: string;
}

/* Auth */

export interface User {
    id: string;
    name: string;
    email: string;
    role: Role;
    messId: string;
    messName: string;
}

export interface AuthResponse {
    accessToken: string;
    refreshToken: string;
    user: User;
}

/* API Responses */

/** One member's meal status for the headcount detail view */
export interface HeadcountMember {
    id: string;
    name: string;
    /** 0 = not eating, 1+ = number of portions */
    count: number;
    /** number of guests this member brought (only relevant when count > 0) */
    guestCount: number;
    /** false = member has no log entry (defaulted to ON) */
    hasLog: boolean;
}

export interface HeadcountSlot {
    memberCount: number;
    guestCount: number;
    total: number;
    cutoffTime: string;    // HH:MM
    cutoffPassed: boolean;
    /** Per-member breakdown for the detail panel */
    members: HeadcountMember[];
    /** Optional cook's note for what was prepared this slot */
    cookNote?: string | null;
}

export interface HeadcountResponse {
    messName: string;
    date: string;
    // Backward-compat top-level (lunch-based, used by overview)
    memberCount: number;
    guestCount: number;
    totalHeadcount: number;
    source: "database";
    slots: {
        breakfast: HeadcountSlot;
        lunch: HeadcountSlot;
        dinner: HeadcountSlot;
    };
}

export interface ExpenseResponse {
    id: string;
    messId: string;
    memberId: string;
    memberName: string;
    amount: number;
    category: ExpenseCategory;
    description: string | null;
    date: string;
    createdAt: string;
    liveMealRate: number;
}

export interface BazaarItem {
    category: ExpenseCategory;
    amount: number;
    description?: string;
}

/** A saved photo of the paper memo. The picture itself is fetched separately. */
export interface BazaarMemoInfo {
    id: string;
    mimeType: string;
    sizeBytes: number;
    createdAt: string;
}

export type BazaarEntryMode = "ITEMIZED" | "MEMO_TOTAL";

export interface BazaarSessionResponse {
    id: string;
    messId: string;
    date: string;
    yearMonth: string;
    shoppers: Array<{ id: string; name: string }>;
    note: string | null;
    /** ITEMIZED = typed line items; MEMO_TOTAL = photo of the memo plus one total */
    entryMode: BazaarEntryMode;
    memos: BazaarMemoInfo[];
    createdByName: string | null;
    total: number;
    isVoided: boolean;
    voidReason: string | null;
    voidedAt: string | null;
    items: Array<{
        id: string;
        category: ExpenseCategory;
        amount: number;
        description: string | null;
    }>;
    createdAt: string;
}

export interface ContributionResponse {
    id: string;
    memberId: string;
    memberName: string;
    amount: number;
    note: string | null;
    date: string;
    recordedByName: string | null;
    createdAt: string;
    isVoided: boolean;
    voidReason: string | null;
    voidedAt: string | null;
}

export interface MonthMatrixResponse {
    messId: string;
    messName: string;
    yearMonth: string;
    startDate: string;
    endDate: string;
    isClosed: boolean;
    /** Nearest existing periods before and after this one (null at either end) */
    prevYearMonth: string | null;
    nextYearMonth: string | null;
    mealRate: number;
    totalExpense: number;
    /** Billable meals across the mess (the meal-rate denominator) */
    totalMeals: number;
    totalGuestMeals: number;
    guestMealPolicy: GuestMealPolicy;
    /** Whether closing this month carries balances into the next one */
    carryForwardBalance: boolean;
    /** JS weekday numbers (0 = Sunday) the mess counts as weekend */
    weekendDays: number[];
    members: MemberMatrixRow[];
}

export interface MemberMatrixRow {
    memberId: string;
    memberName: string;
    memberRole: string;
    isGuest: boolean;
    guestFrom?: string;
    guestUntil?: string;
    days: DayEntry[];
    ownMeals: number;
    guestMeals: number;
    /** Billable meals for this member (own + guests under the HOST policy) */
    totalMeals: number;
    totalAmount: number;
    contributed: number;
    balance: number;
}

export interface DayEntry {
    logId: string;
    memberId: string;
    memberName: string;
    date: string;
    breakfastCount: number;
    lunchCount: number;
    dinnerCount: number;
    breakfast: boolean;
    lunch: boolean;
    dinner: boolean;
    guestCount: number;
    /** Guest portions that day (guests × meals the host ate) */
    guestMeals?: number;
    frozen: boolean;
}

/** HOST = guest meals are charged to the member who brought them; SHARED = spread across the mess */
export type GuestMealPolicy = "HOST" | "SHARED";

export interface MessSettingsResponse {
    name: string;
    cutOffTime: string;
    estimatedMonthlyBudget: number | null;
    monthStartDay: number;
    timezone: string;
    guestMealPolicy: GuestMealPolicy;
    bazaarCountsAsDeposit: boolean;
    carryForwardBalance: boolean;
    /** JS weekday numbers (0 = Sunday … 6 = Saturday) counted as WEEKEND */
    weekendDays: number[];
    /** New members wait for an admin before they can sign in */
    requireJoinApproval: boolean;
    plan: string;
}

/* API Requests */

export interface LoginRequest {
    email: string;
    password: string;
}

export interface RegisterRequest {
    /** create = start a new mess and become its admin; join = use an invite code */
    mode: "create" | "join";
    name: string;
    email: string;
    phone?: string;
    password: string;
    messInviteCode?: string;
    messName?: string;
    locale?: string;
}

/** Register answers with a session, or with `pending` when the admin must approve the join first */
export type RegisterResponse =
    | (AuthResponse & { pending?: undefined; inviteCode?: string })
    | { pending: true; messName: string };

export interface SupportMessage {
    id: string;
    authorType: "USER" | "STAFF" | "SYSTEM";
    authorName: string;
    body: string;
    createdAt: string;
}

export interface SupportTicket {
    id: string;
    name: string;
    email: string;
    category: string;
    subject: string;
    status: "OPEN" | "WAITING_ON_USER" | "RESOLVED" | "CLOSED";
    priority: "LOW" | "NORMAL" | "HIGH";
    messId: string | null;
    memberId: string | null;
    createdAt: string;
    updatedAt: string;
    messages?: SupportMessage[];
}

export interface ExpenseRequest {
    messId: string;
    memberId?: string;
    amount: number;
    category: ExpenseCategory;
    description: string;
    date: string;
}

export interface BazaarSessionRequest {
    date: string;
    shoppers: Array<{ id: string; name: string }>;
    note?: string;
    /** Defaults to ITEMIZED */
    mode?: BazaarEntryMode;
    /** ITEMIZED: the line items */
    items?: BazaarItem[];
    /** MEMO_TOTAL: the total printed on the memo */
    total?: number;
    /** Base64 photos (no data: prefix). Required for MEMO_TOTAL, optional proof for ITEMIZED. */
    memos?: Array<{ data: string }>;
}

export interface ContributionRequest {
    memberId: string;
    amount: number;
    note?: string;
    date: string;
}

export interface MealToggleRequest {
    memberId: string;
    date: string;
    slot: MealSlot;
    /** Integer count: 0 = off, 1 = normal, 2+ = extra. Preferred over `status`. */
    count?: number;
    /** Legacy boolean — converted to count 0/1 on the server. */
    status?: boolean;
}

export interface GuestUpdateRequest {
    memberId: string;
    date: string;
    guestCount: number;
}

export interface CloseMonthRequest {
    messId: string;
    adminId: string;
    yearMonth: string;
    nextManagerId?: string;
}

export interface MessSwitchResponse {
    accessToken: string;
    refreshToken: string;
    mess: { id: string; name: string };
}
